### ISSUE TITLE
Germanic: Language Group "Diaspora German" does not appear in the LgsxWds/ WdsxLgs view

### ISSUE THREAD

**Issue by LauraWae** [sndcomp/website#101]

**Comment by runjak** [comment]
When I opened LgsxWds view Diaspora German was selected. When switching to WdsxLgs view I lost some part of the selection, notably 'Diaspora German'. When I added 'Diaspora German' to WdsxLgs view, I found that there are some many languages in that group that the table breaks if I don't hide the  side menus and remove all other groups.
![table](https://cloud.githubusercontent.com/assets/5417642/6843577/abc66164-d3a4-11e4-8dde-4c2e2db889ef.png)
