### ISSUE TITLE
Andean study groups: in the boxes, I cannot deselect language set "Viñac"

### ISSUE THREAD

**Issue by LauraWae** [sndcomp/website#102]

**Comment by runjak** [comment]
I think I've managed to isolate this issue. For some reason it appears that the ShortName for 'Víñac' is not unique, but that somehow both, 'Víñac' and 'Víñac 2' have the same entry for ShortName. I'll need to figure out where the ' 2' suffix comes from, and that I make the correct distinction between the two. I expected this issue to also turn up for 'La Jalca' and 'La Jalca 2', but somehow these are stored as different entries in the table.
![vinac](https://cloud.githubusercontent.com/assets/5417642/6844267/572c7156-d3aa-11e4-9f4d-02b9c2e2bcb8.png)

**Comment by runjak** [comment]
Okay, so I misunderstood the database - there's actually three entries here, and it appears that 'Víñac' is indeed duplicate in there…
![v](https://cloud.githubusercontent.com/assets/5417642/6844479/256be636-d3ac-11e4-9f47-9b42c7a4ccf5.png)

**Comment by runjak** [comment]
@PaulHeggarty just updated the database, which fixes this :)
