### ISSUE TITLE
Downloading multiple sound files doesn't work.  It times out before it works.

### ISSUE THREAD

**Issue by PaulHeggarty** [sndcomp/website#122]

**Comment by runjak** [comment]
I may be able to build a solution for this using [JavaScript](https://stackoverflow.com/questions/3665115/create-a-file-in-memory-for-user-to-download-not-through-server) and [jszip](https://stuk.github.io/jszip/). This would mitigate the server timeout and put the whole work for zipping on the client.

**Comment by runjak** [comment]
I'm thinking about using a combination of these three:
1: [FileSaver.js](https://github.com/eligrey/FileSaver.js) (aids saving files from js)
2: [Blob.js](https://github.com/eligrey/Blob.js) (increases compatibility for FileSaver.js)
3: [JSZip](https://stuk.github.io/jszip/) (zipping ftw!)
