### ISSUE TITLE
We need a way (an icon?) to allow users to zoom the map to a particular language set, e.g. Ireland or Brittany in the new Celtic languages family.  

### ISSUE THREAD

**Issue by PaulHeggarty** [sndcomp/website#138]
The zoom should ideally be calculated automatically, to include all languages that are members of that language set.

**Comment by runjak** [comment]
We could use the same icon here as we use to allow zooming in on a particular language,
just that it would be placed behind the language set in the left menu, and would zoom in on the bounding box of the languages in the set.
