### ISSUE TITLE
Romance view: When clicking the one-language-view of any language in Romance, the site always shifts to "Ladino: Dolimites"

### ISSUE THREAD

**Issue by LauraWae** [sndcomp/website#166]

**Comment by runjak** [comment]
Ah, thanks for the bug report!
I understand that you're talking about the '1L' links in the left menu as shown below?
![screenshot_2015-07-08_09-58-07](https://cloud.githubusercontent.com/assets/5417642/8565671/eb98c93a-2557-11e5-88c3-486ad6c1b6dc.png)
Or is this about the topmenu?
![screenshot_2015-07-08_09-58-22](https://cloud.githubusercontent.com/assets/5417642/8565673/ecc22400-2557-11e5-9de6-038ee29f6be1.png)
Can you help me with a screenshot or a closer description of where to click to reproduce this problem?

**Comment by LauraWae** [comment]
Hi,
It happens when you switch from the map view to the one-language-view in
the topmenue. Apart from showing the wrong language, it also happens that
the sidebar menue somehow stops working properly: it cannot be pulled down
more than to the "Alpes"box.
I hope this helps.


2015-07-08 10:02 GMT+02:00 Jakob Runge <notifications@github.com>:

**Comment by runjak** [comment]
It appears that I can no longer reproduce this problem and it was probably solved as a side effect of something else. I will therefore close it now.
