### ISSUE TITLE
Contributors: Adrian Clement is listed in the list of Slavic, however, he edited Romace and Germanic files, so this needs to be changed (it also says so in his box)

### ISSUE THREAD

**Issue by LauraWae** [sndcomp/website#169]

**Comment by runjak** [comment]
Yes, the mistake here can also be seen in the database:
![ac](https://cloud.githubusercontent.com/assets/5417642/9899944/73c8cf08-5c5d-11e5-842b-c5d12dfa01dd.png)
![categories](https://cloud.githubusercontent.com/assets/5417642/9899945/73cd3b38-5c5d-11e5-8515-05b7f01e2261.png)
Supposedly the `SortGroup` for Adrian should be `12`, and I'll change it to that on the server.
But in addition @PaulHeggarty will have to update his data set to make sure the record for Adrian isn't overwritten by accident later.
My fix looks like this: `UPDATE Contributors SET SortGroup = 12 WHERE Forenames = 'Adrian';`
