### ISSUE TITLE
[Andean] On the  right side menu, only a few words can be reproduced/appear in blue, although they are working in the central table (see foto for an example)

### ISSUE THREAD

**Issue by LauraWae** [sndcomp/website#197]
![unbenannt](https://cloud.githubusercontent.com/assets/10007762/9658954/7ce6744c-524d-11e5-9c62-015cc947a9c3.JPG)

**Comment by runjak** [comment]
The reason for this is that the transcriptions for the word menu are taken from ```Ancestral-Quechua``` while the ones in the table come from ```Cuzco: Occobamba```.
Although it may not be intuitive this is how it should work .)
![screenshot_2015-09-07_13-46-18](https://cloud.githubusercontent.com/assets/5417642/9716154/6ca3b316-5567-11e5-9d5c-3b2f00b08954.png)
