### ISSUE TITLE
Can't enter the Mapdungun study site

### ISSUE THREAD

**Issue by LauraWae** [sndcomp/website#199]
When I choose "Mapudungun" in the language family selection menu, nothing happens.

**Comment by runjak** [comment]
I believe that this might have been a side effect of something else being broken.
Is this still broken for you?

**Comment by LauraWae** [comment]
Ok, es funktioniert wieder. Danke.

2015-09-07 14:36 GMT+02:00 Jakob Runge <notifications@github.com>:

**Comment by runjak** [comment]
Wunderbar :)
