### ISSUE TITLE
Do a check to prevent any translations beginning with a space character " ", because this makes words appear in the wrong order when sorted alphabetically.

### ISSUE THREAD

**Issue by PaulHeggarty** [sndcomp/website#201]

**Comment by runjak** [comment]
I've executed ```2015-09-07_migration.sql``` from a5754e7b072d8920f336b2ab1f1c66b08abfa2a2 against the database, to clean all current whitespace. Together with 6b72633273649e55cffc72128e235545fe541ab6 this means that there should no longer be any trailing/leading whitespace in the database.
