### ISSUE TITLE
Return Andean language sets to their earlier correct system of separating by family, do not lump them all under "Andes (All Rfc)"

### ISSUE THREAD

**Issue by PaulHeggarty** [sndcomp/website#202]

**Comment by runjak** [comment]
Are you aiming to have something like this, just with headlines or something to indicate families?
![screenshot_2015-09-05_18-01-16](https://cloud.githubusercontent.com/assets/5417642/9700114/2a8566fc-53f8-11e5-82b3-cd6c65ae1abc.png)

**Comment by runjak** [comment]
I think this may be related to some entries missing from the Families table.
I've found a lead for that by inspecting older states of site+database I had on my computer.
Maybe I can fix part of this directly :)

**Comment by PaulHeggarty** [comment]
Hi Jakob,

No, that's not what we used to have, and not what we need.  Your image has
about 20 different coloured boxes, but does not group into families.   

Currently, on the broken site, there are two colour boxes only:  grey for
all Andes, blue for Mapudungun.

What we used to have, and need again, is four colour boxes (not two as now,
not c. 20 as in your new image):  Quechua, Aymara, Uru-Chipaya, Mapudungun.
= Family Ix values 1, 2, 3, 8.

Within each are the corresponding regional subgroups -- which I think were
not coloured originally, and don't bother with that.

Remember that this is to do with the difference between studies like the
whole Andes 2-0 (0= for all families within study 2), and Mapudungun which
is specifically 2-8.  Where there's only one family, like for Mapudungun, we
can colour by sub-groups within that family.  Where there are multiple
families, we can only colour by family.

As I said, it used to be like this, we just need to get back to that.

All the best,

   Paul

 

 

 

  _____

**Comment by runjak** [comment]
![screenshot_2015-09-05_18-24-18](https://cloud.githubusercontent.com/assets/5417642/9700208/565e3b7a-53fb-11e5-8dbb-e8b8c8d13005.png)
When viewing the current Families table, it becomes apparent that entries like Uru-Chipaya are missing.
I've compiled a list of all forms of entries I've found for the families table over this year:
![older](https://cloud.githubusercontent.com/assets/5417642/9700218/89d81c0a-53fb-11e5-96d1-c8488da32b31.png)

**Comment by runjak** [comment]
Yes, thanks for the comment. I see that now. I think I can 'restore' the latest entries for Uru-Chipaya and the others.

**Comment by runjak** [comment]
Ok, what about a Language menu like this:
![screenshot_2015-09-05_18-31-34](https://cloud.githubusercontent.com/assets/5417642/9700254/781d7194-53fc-11e5-95b1-2d299dbb8a34.png)
To achieve this I would alter the Families table as follows:
![screenshot_2015-09-05_18-31-45](https://cloud.githubusercontent.com/assets/5417642/9700258/84e3072c-53fc-11e5-9d4f-d879311e9431.png)

**Comment by runjak** [comment]
Also good news: I think I can apply the changes for this table directly without @Bibiko trough the SQL upload feature. I would still need his help for applying 87aca54c84b4548852e143b82d2826102b2ba51e though.

**Comment by PaulHeggarty** [comment]
Hi Jakob,

Yes, that's it, the new menu image is right!

Paul

 

Ok, what about a Language menu like this:
 
<https://cloud.githubusercontent.com/assets/5417642/9700254/781d7194-53fc-11
e5-95b1-2d299dbb8a34.png> screenshot_2015-09-05_18-31-34
To achieve this I would alter the Families table as follows:
 
<https://cloud.githubusercontent.com/assets/5417642/9700258/84e3072c-53fc-11
e5-9d4f-d879311e9431.png> screenshot_2015-09-05_18-31-45

-
Reply to this email directly or view
<https://github.com/sndcomp/website/issues/202#issuecomment-137972888>  it
on GitHub.
<https://github.com/notifications/beacon/AIaUxhPGRaQFtP-VennrwK6Tt_F8QMmsks5
ouxC2gaJpZM4F4b-K.gif>

**Comment by runjak** [comment]
Good news :)
I've put the SQL file to fix this in the database repository at commit f51434e7182bcba6f626277cda89770d8e2db43d, so that I can find it again.

**Comment by PaulHeggarty** [comment]
Hi

I've uploaded the corrected table and it's working, except for Uru-Chipaya.
I can't see why it's not working, and I really would like it to, because
that's the weirdest phonetics of any language, so I particularly like
demonstrating it.  It's also hard data to get, so I want to show it off!

Can you work out why it's not showing?

Thanks!

Paul

 

 

  _____

**Comment by runjak** [comment]
I think the problem here is that the Region 'Chipaya' with an id of ```2301``` doesn't appear to be linked to the Language 'Chipaya:  Aransaya' with LanguageIx ```23221005009```. This may be because there is currently no entry in the RegionLanguages_Andean table where LanguageIx is ```23221005009```. I'll investigate further…

**Comment by runjak** [comment]
A query like ```INSERT INTO RegionLanguages_Andean (StudyIx, FamilyIx, SubFamilyIx, RegionGpIx, RegionMemberLgIx, LanguageIx, Include) VALUES (2,3,0,1,1,23221005009,1);``` appears to solve the problem, and produces a menu like this:
![screenshot_2015-09-05_19-20-56](https://cloud.githubusercontent.com/assets/5417642/9700443/42d4080c-5403-11e5-9f80-58e8993e5369.png)
From my perspective this implies that the corresponding entry linking the 'Chipaya' region with its languages was missing from ```RegionGroupMemberLanguages_Andean.txt``` when it was last imported.

**Comment by runjak** [comment]
I've applied this change to the sndcomp website.
Please confirm that the issue is resolved.
The database repository has a commit for this with the hash 1cd2cdbbd294dbb9151f4130d736565f5c2b1ae7.

**Comment by Bibiko** [comment]
Hi. I'm on the road. I'll be at home in about hours. Then I'll apply the git update.

Cheers, Hans

**Comment by runjak** [comment]
Awesome :)

**Comment by Bibiko** [comment]
Home. I've  just updated the web site. Please check whether everything works.

Cheers, Hans

**********************************************************
Hans-Joerg Bibiko
Max Planck Institute for the Science of Human History
Department of Linguistic and Cultural Evolution / Room 111
Kahlaische Str. 10	phone:	+49 (0) 3641 686 871
D-07745 Jena		fax:	+49 (0) 3641 686 990
Germany			e-mail:	bibiko [at] shh.mpg.de
**********************************************************

**Comment by runjak** [comment]
Looks good so far, thanks a lot :)
@PaulHeggarty if you don't want ```Quechua``` to show up as its own study, make sure it's not present in the studies table.
