### ISSUE TITLE
Drop down phonetics language box overlaps with scroll bar in word selector column

### ISSUE THREAD

**Issue by PaulHeggarty** [sndcomp/website#206]

**Comment by runjak** [comment]
The wanted solution for this is to only use the scroll bars for things below these screenshots:
![screenshot_2015-09-09_15-56-32](https://cloud.githubusercontent.com/assets/5417642/9763717/6217eb92-570b-11e5-9fb8-4ab555cd6150.png)
![screenshot_2015-09-09_15-56-38](https://cloud.githubusercontent.com/assets/5417642/9763718/622f670e-570b-11e5-8e93-4ddf7c276246.png)

**Comment by runjak** [comment]
Currently [Renderer.js](https://github.com/sndcomp/website/blob/master/js/views/render/Renderer.js#L96-L105) with its `nanoScroller()` method takes care of initializing and (re-)sizing scrollbars. This will have to be done in the respective views for the side menus. I'll also have to move the `.nano` and `.nano-content` classes further down the template structure.
