### ISSUE TITLE
Romance site now fails, after uploading new transcriptions SQL files

### ISSUE THREAD

**Issue by PaulHeggarty** [sndcomp/website#237]

**Comment by runjak** [comment]
Trying to fetch the [JSON](http://lingweb.eva.mpg.de/sndcomp/query/data?study=Romance) reveals the problem with Romance:
![fail](https://cloud.githubusercontent.com/assets/5417642/10277959/0c4915e8-6b5a-11e5-9617-d174ed351824.png)

**Comment by runjak** [comment]
I've started working on a script named `regenerateCache.php` that may be run as a cron job, or even be forked off of the main site admin area, to aid this problem.

**Comment by runjak** [comment]
We've had this same problem in issue #97.
