### ISSUE TITLE
Romance: In the German translation of the site, on the left bar menu, there appear two boxes titled "Historical".

### ISSUE THREAD

**Issue by LauraWae** [sndcomp/website#248]
Jetzt auf deutsch: Es gibt eine "Historisch"-Box zu viel auf der dt. Version der Seite. Die Sprachen erscheinen so alle um eine Box nach oben verschoben: Die Sprachen von "Iberische Halbinsel" befinden sich in der zweiten "Historisch"-Box, die Sprachen Frankreichs in der "Iberische Halbinsel"-Box etc. Auf Englisch ist alles fein.

**Comment by runjak** [comment]
![screenshot_2015-10-19_14-21-55](https://cloud.githubusercontent.com/assets/5417642/10577589/c67781d0-766c-11e5-8dfd-f9f646b10f77.png)
Ja, das gehört in der Tat nicht so.

**Comment by runjak** [comment]
Durch Suchen im Translation Interface gefunden:
![translation](https://cloud.githubusercontent.com/assets/5417642/10632660/1efd08e6-77e6-11e5-9fd1-af2a0558c06c.png)
Aus irgendeinem Grund wird 'Iberia' mit 'Historisch' übersetzt, daher der Fehler.
Ich habe den Eintrag auf 'Iberien' korrigiert.
