### ISSUE TITLE
In the German translation, the language set and word set names still appear in English, as do all the language names in the language selector column. Presumably they were deleted from the translation at some point. 

### ISSUE THREAD

**Issue by PaulHeggarty** [sndcomp/website#50]

**Comment by runjak** [comment]
It appears that 2014-10-07 was the last date where more than 0 entries for German dynamic translation resided in the db. I'll restore them from there.

**Comment by runjak** [comment]
I've found the missing translations and inserted them into the database again. There is a known-good backup named 150313.sql
