### ISSUE TITLE
The site is not loading at all

### ISSUE THREAD

**Issue by LauraWae** [sndcomp/website#83]

**Comment by runjak** [comment]
I can open both, the main website on lingweb and the admin area that belongs to it in my browser. Is this still an issue for you? If so can you tell me which browser you're using, so that I can try to figure out where the problem might be?

**Comment by LauraWae** [comment]
Yes, it is still an issue today. I am using firefox.

**Comment by runjak** [comment]
Is this a machine at MPI where I can possibly have a look at it, or is this happening to you somewhere else? I'll be in Thursday+Friday. As an alternative you could probably help me with a copy of the debug output. To do that you'll need to perform the following steps:
1: Press Ctrl+Shift+K when in Firefox to open the web console. It should look something like this:
![webconsole](https://cloud.githubusercontent.com/assets/5417642/6685864/0fa1dc76-cc9e-11e4-9426-c7ab983ddcbf.png)
2: Right click on it, select all
3: Right click -> copy
4: Paste the content of the console as a comment here

The web console only contains data relevant for the currently open tab. So it won't hand over information related to any other website you might visit at the same or a different time.

As a third thing you could try if it helps to clear your browser cache, like described on [refreshyourcache.com]( http://www.refreshyourcache.com/en/firefox-20/)

**Comment by LauraWae** [comment]
Hi Jakob,
Thanks. Now it seems to be working.

2015-03-17 12:11 GMT+01:00, Jakob Runge <notifications@github.com>:

**Comment by runjak** [comment]
Nice to know that this issue is resolved. I fear that it may be part of a problem that can occur during updates. Ideally we wouldn't need the cache refresh to make sure that the website works.
