### ISSUE TITLE
Map: Germanic recordings from Cloppenburg, Husum and Veenkolonials appear in the Gulf of Guinea :)

### ISSUE THREAD

**Issue by LauraWae** [sndcomp/website#89]

**Comment by runjak** [comment]
'SELECT ShortName FROM Languages_Germanic WHERE Latitude = 0 or Longtitude = 0' produces exactly the same list. It appears that this is a case for @PaulHeggarty to solve. Such cases should become easier to spot once #66 is implemented.

**Comment by PaulHeggarty** [comment]
Hi Laura,

Thanks for this.  Whenever a language does, this, it means that the latitude
and longitude values are not specified for that language, and default to
zero.  Jakob is building a way to test for this automatically, but in the
meantime, if you see a language in the Gulf of Guinea, then please look up
its latitude and longitude values and email them to me so I can fix this.

Could you do this for these three, please?  Veenkoloniaals is the adjective
of the place, so you might have to try a few different forms.  It's
somewhere in northern Netherlands or Germany.

Paul

 

 

  _____
